name: E2E Tests

on:
  pull_request:
    branches:
      - master
  push:
jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test -i --no-parallel

#      - uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: "Test Results"
#          path: build

#      - uses: actions/upload-artifact@v2
#        with:
#          name: "Compiled artifacts for Pull Request #${{github.event.number}}"
#          path: build/libs
